### ISSUE TITLE
component esphome.coroutine took to long time for operation

### ISSUE THREAD

**Issue by mitzzz** [echavet/MitsubishiCN105ESPHome#178]
Installed your code and everything has worked fine for a day but im getting spammed with this in the log:

![zrXERX1](https://github.com/user-attachments/assets/7ab0b0d5-b360-4363-8212-bbc190d46280)

is there a worry?

**Comment by echavet** [comment]
Hi @mitzzz 
No, there is no pb. This is just that the ship is slow ant it has to do much stuff to deal with the unit. Perhaps you could get rid of these messages by setting the logs level to warning.
