### ISSUE TITLE
Request: Support Purifier mode

### ISSUE THREAD

**Issue by duhow** [echavet/MitsubishiCN105ESPHome#179]
I have the unit [MSZ-AY35VGKP](https://www.mitsubishielectric.es/aire-acondicionado/producto/aire-acondicionado/msz-ay/) / MUZ-AY35VG which contains an air purifier filter.

There's a button in the remote control named "✨ Purifier".

I can help and provide any additional input to enable supporting this :)

**Comment by echavet** [comment]
Hi @duhow 
Thanks for your contribution.
I close this as it is not an issue
If you want to, you can publish a thread in the discussion section.
