### ISSUE TITLE
Please make RX/TX configurable for ESP32 one way or the other :-)

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#5]
Hi, 

great work so far!
I would rather use your component for my Mitsubishi components than others. 

I am using a M5Stack ATOM Lite:
<img width="379" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/15a648fe-0be4-4f71-8cd2-7e178fce309a">

with a groove cable:
<img width="358" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/cd7791e6-2a1a-4d50-b074-69a4212f03f8">

For connecting the Atom Lite to the Mitsubishi device I removed the white connector on one end of the groove cable (now I use 50 cm cables for some devices) and inserted the four metal clamps of the cables to a CN105-Connector:
<img width="361" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/c0de7dda-feba-427d-a0ac-78743e422f78">

So I have just the ATOM Lite with the cable that you can directly connect to the Mitsubishi device, nothging more (keep it simple and easy)

(about ESP32 and 5V-Input for GPIO see: https://github.com/bdring/6-Pack_CNC_Controller/issues/31 )

BUT: the ATOM Lite uses GPIO26 and GPIO32
<img width="297" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/760e2ba9-ace4-44fa-be67-abaa3575fb45">

I am right now using the fork from wrouesnel, because he allowed to change the RX/TX pin here:
https://github.com/wrouesnel/esphome-mitsubishiheatpump/commit/127d2a0ef9b4e755026a8e1fdf2e510200f3a986

```
climate:
  - platform: mitsubishi_heatpump
    id: hp
    name: "${friendly_name}"
    hardware_uart: UART1
    tx_pin: 32
    rx_pin: 26
    baud_rate: 2400
```

Would it be possible to add that possibility as well in your fork?

Or... could you maybe revert the UART part of the custom integration back to the original ESPHome UART-Implementation?
According to https://esphome.io/components/uart.html the problems with the parity have been fixed for the ESP8266: 

> From ESPHome 2021.8 the ESP8266SoftwareSerial UART write_byte function had the parity bit fixed to be correct for the data being sent. This could cause unexpected issues if you are using the Software UART and have devices that explicity check the parity. Most likely you will need to flip the parity flag in YAML.
> parity (Optional): The parity used on the UART bus. Options: NONE, EVEN, ODD. Defaults to NONE.

... that way the component would follow more the ESPHome standards and everybody could use the ESPHome UART component to config the pins...

Cheers from good old Germany, 
Sebastian

**Comment by echavet** [comment]
Hi,
Thanks for your mail.
I've just committed changes for your ask.

could you please test, because I don't have any device to check it's ok.

don't forget to add the refresh options to force update to head

external_components:
- source: github://echavet/MitsubishiCN105ESPHome
refresh: 0s

**Comment by Bascht74** [comment]
Will check…

**Comment by Bascht74** [comment]
Compile failed:

```
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/climate/climate.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/climate/climate_mode.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/climate/climate_traits.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/cn105/climateControls.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/cn105/cn105.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/cn105/componentEntries.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/cn105/extraComponents.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/cn105/heatpumpFunctions.cpp.o
Compiling .pioenvs/klima-og-tim/src/esphome/components/cn105/hp_readings.cpp.o
src/esphome/components/cn105/cn105.cpp: In member function 'void CN105Climate::setupUART()':
src/esphome/components/cn105/cn105.cpp:126:37: error: 'class HardwareSerial' has no member named 'pins'; did you mean 'find'?
             this->get_hw_serial_()->pins(this->tx_pin_, this->rx_pin_);
                                     ^~~~
                                     find
*** [.pioenvs/klima-og-tim/src/esphome/components/cn105/cn105.cpp.o] Error 1
========================= [FAILED] Took 31.55 seconds =========================
```

**Comment by echavet** [comment]
Ok thanks
Sorry for that...

**Comment by echavet** [comment]
the HardwareSerial class is not the same for ESP32 and ESP8266:

so I changed this:

```
#ifdef ESP8266
            this->get_hw_serial_()->begin(this->baud_, SERIAL_8E1);
            this->get_hw_serial_()->pins(this->tx_pin_, this->rx_pin_);
#elif defined(ESP32)                        
            this->get_hw_serial_()->begin(this->baud_, SERIAL_8E1, this->tx_pin_, this->rx_pin_);
#endif
```

you can try again

**Comment by Bascht74** [comment]
It works, but I had to change / RX/TX. Could you change to: 

this->get_hw_serial_()->begin(this->baud_, SERIAL_8E1, this->rx_pin_, this->tx_pin_);
See: https://microcontrollerslab.com/esp32-uart-communication-pins-example/ (first parameter is rx ) 

:-)

Except that, it works with basic configuration. 
I will check more this evening and will migrate all devices…

**Comment by echavet** [comment]
done
thanks for your help

**Comment by Bascht74** [comment]
Thx, working now!

I see that you updated the readme! Thx!

Just one question: 

You wrote:

> Note: The update_interval is set here to 4s for debugging purposes. However, it is recommended to use a interval longer or equal to 1s because the underlying process divides this interval into three separate requests.

What do you suggest for the update_interval?
You said 4s for debugging (so that not that many messages will come in the log), and for normal operation and "snappy", quick update in Home Assistant of the local remotes just 1s?

**Comment by echavet** [comment]
1 second seems like a good interval if your logs aren't set to be too verbose. The method buildAndSendRequestsInfoPackets defines 2 sub-intervals within update_interval_ by taking the longer of 300 ms or (update_interval_ / 4). This is likely to evolve based on user feedback. Maybe on this, GeoffDavis's choice is better...
Regardless, 3 types of information requests are sent between 2 intervals.
So setting it to 1 second actually equates to 250-300 ms in reality.

**Comment by Bascht74** [comment]
Thx, one second is fine with me...

**Comment by tchlyah** [comment]
Thanks @Bascht74 for testing and validating this. Can you please share the yaml file you used with this configuration? 

Also, would this cable work without modification?

https://a.aliexpress.com/_EHBf4kw

Thanks !
