### ISSUE TITLE
Component esphome.coroutine took a long time for an operation (75 ms)

### ISSUE THREAD

**Issue by c-mholm** [echavet/MitsubishiCN105ESPHome#86]
I get this yellow warning/error every cycle the code loops. I tried to google it but seems like there is no universal fix but maybe something that needs to be addressed in the Mitsubishi code for ESPHome? Anyone else getting this?

esp32dev
Firmware: [MitsubishiCN105ESPHome](https://github.com/echavet/MitsubishiCN105ESPHome)
Connected to GPIO1 and GPIO3

<img width="1171" alt="Screenshot 2024-05-08 at 13 49 36" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/80196654/907b1838-074c-4638-b9cf-15e8897b23e3">

**Comment by echavet** [comment]
This is "normal" behaviour. The component should not block the esphome framework for a too long period but if you keep the logs active you can't deal without this warning. Actually I couldn't!!!

However, even without any log, some chips take too much time according to the esphome framework!

I could try to optimise again and again by limiting the number of operations at each loop. But I think it is not worth the pain.

**Comment by c-mholm** [comment]
Ok. That’s what I thought. Read about a lot of different implementations with the same message. Everything seems to work so we just have to live with it. My ocd is just not happy with yellow text in the log :)
